### ISSUE TITLE
muscat_analysis don't accept DICE annotation

### ISSUE THREAD

**Issue by obotman** [HelenaLC/muscat#120]
Hello,
I've annotated my sce with BlueprintDB database in SingleR and it's working.
When I try to run muscat_analysis on the same sce annotated with DICE database, muscat stop the analysis during calcExprFreqs.
But I'm able to run "manually" get_DE-info().
I've fully compare the two databases but I don't find the bug. 

Error Message :
Error in `rownames<-`(`*tmp*`, value = all_genes) :
  attempt to set 'rownames' on an object with no dimensions
In addition: Warning message:
In FUN(X[[i]], ...) :
  For Celltype NA gene names got lost while calculating the fraction of expression of each gene with muscat::calcExprFreqs (due to a bug in this function). We temporality fixed this ourselves for the moment.

Any idea?

Best regards,
Olivier

**Comment by HelenaLC** [comment]
Please provide a reproducible example, otherwise this is hard to understand and I can not help… also I’m struggling with understanding a couple sentences. E.g., what do you mean by “for celltype NA gene names got lost”? Have you tried setting these to something like “untitled”?

**Comment by HelenaLC** [comment]
NA gene name? I thought you said celltype name? …please be specific. - no, I didn’t mean uploading the data. But putting line by line the code leading up the error as well as relevant intermediate outputs that might help understand what’s causing the issue.

**Comment by HelenaLC** [comment]
muscat_analysis is not part of the muscat package, so I have no idea what it is doing. If you wrote it as a wrapper, please provide the code that is actually being run.

**Comment by obotman** [comment]
I'm sorry for this misunderstanding. Anyway, thank you for your help. I will ask to the muscatWrapper developer.
Best regards,
Olivier

**Comment by HelenaLC** [comment]
Yes, agreed. I wasn’t aware there was sich a package… I’m curious though: Why use a muscat wrapper when it’s a couple lines to run the analysis yourself? Should be easier to also understand any issues that might occur… I don’t see the benefit here, because muscat is already a wrapper around pseudobulking+edgeR (for example).

**Comment by obotman** [comment]
I'm sorry to insist but I would like to understand what happen so I redo the analysis with your pipeline.
I obtain exactly the same "pb" objects with two differents celltype annotations (group_id).
When I run pbMDS() withonecelltype annotation I got this error message:
```
Error in if (median(f75) < 1e-20) { :
  missing value where TRUE/FALSE needed
In addition: Warning message:
In DGEList(unname(y), remove.zeros = TRUE) : library size of zero detected
```
Why I've a library with zero size from on celltype annotation and not with the others?

```
sce <- as.SingleCellExperiment(seuObjFull, assay="SCT")
sceDICE <- prepSCE(sce1, kid = "annotationSubDICE",gid = "treatment",sid = "SampleID",drop = TRUE)
nkDICE <- length(kidsDICE <- levels(sceDICE$cluster_id))
nsDICE <- length(sidsDICE <- levels(sceDICE$sample_id))
names(kidsDICE) <- kidsDICE; names(sidsDICE) <- sidsDICE
sceBlue <- prepSCE(sce1, kid = "annotation",gid = "treatment",sid = "SampleID",drop = TRUE)
nkBlue <- length(kidsBlue <- levels(sceBlue$cluster_id))
nsBlue <- length(sidsBlue <- levels(sceBlue$sample_id))
names(kidsBlue) <- kidsBlue; names(sidsBlue) <- sidsBlue

# # Data overview
t(table(sceDICE$cluster_id, sce$sample_id))
t(table(sceBlue$cluster_id, sce$sample_id))

pbDICE <- aggregateData(sceDICE,
    assay = "counts", fun = "sum",
    by = c("cluster_id", "sample_id"))

pbBlue <- aggregateData(sceBlue,
    assay = "counts", fun = "sum",
    by = c("cluster_id", "sample_id"))
```

**Comment by HelenaLC** [comment]
- Zero library sizes mean that some cluster-sample combinations do not express any features. Different annotations will not give the exact same pseudobulks (`pb`), so it is not impossible this might happen.
- Could you perhaps print the output of `table(sce$cluster_id, sce$sample_id)` for the different annotations? Also worth checking the library sizes to see where the evil lies, e.g., via `lapply(assays(pb), \(.) range(colSums(.)))` for both `pbBlue` and `pbDICE`.

**Comment by HelenaLC** [comment]
It's really hard to grasp the data from what you're posting... But I'd say that from the cell counts by cluster-sample you cannot say directly whether or not you have enough cells to run differential analyses. This depends on how many cells there are per group or, otherwise put, how many samples have sufficiently many cells in each group. At the very least, two samples per group (depending on `min_samples`) need to have enough cells (depending on `min_cells`). Then, depending on `filter`ing, these also have non-zero counts for some genes. Overall, it's not as simple as saying "I have enough cells". In addition, I would advice to caution: Even if there are just enough cells, I wonder whether you should "trust" results from testing a hand full of cells across many samples... Instead, a better approach might be do lower the resolution, i.e., merge some biologically similar subpopulation into broader groups such that they have a decent number of cells across all/most samples. Hope that all makes sense?

**Comment by obotman** [comment]
So even if I have enough cells/samples in a cell cluster, I should consider that no pbDS output for that cluster could be due to lack of differential gene expression rather than lack of cells .

**Comment by HelenaLC** [comment]
No, you will get results per gene (p-values, FDR, logFCs) independent of whether or not there's anything differential. But a cluster not being tested (though it has many cells in total) could indicate that there are not enough cells per sample per group... As I said: There need to be at least 2 samples in each group with at least N cells that express a gene.
