### ISSUE TITLE
Vignettes for simulating data

### ISSUE THREAD

**Issue by klanita** [HelenaLC/muscat#16]
Could you please add additional description and examples to the vignettes how to simulate my own examples? So far I couldn't find it anywhere. In case I missed it, could you please point me to it then? Thank you!

**Comment by HelenaLC** [comment]
My apologies, you are correct in that this is missing from the documentation at the moment. I am in fact working on a separate vignette on data simulation since yesterday. 
One I close this issue, please take it as a sign that the vignette has been made available. Hoping to finish it within this week.

**Comment by HelenaLC** [comment]
Apologies for the delay... There are still a lot of things under development, including bug fixes, simplification, but also additions to the current framework. A current (under development and not entirely complete) vignette is now available through the `fix_sim` branch under `vignettes/simulation.rmd`. I hope you can use this for some guidance until the next official Bioc release (~ April) when there'll be an official update & complete documentation.
