### ISSUE TITLE
library size correction

### ISSUE THREAD

**Issue by pseudonym2** [HelenaLC/muscat#63]
Dear team,

thank you for the work you've put up for this package. I have a very simple question as I can't get my head around the source code:
Does the pbDS function automatically perform library size correction? In the vignette it seems that raw counts are being used and no explicit correction to the pseudobulks is done before differential expression analysis.  So can I simply use my raw counts for differential expression analysis and follow the simple code, provided in the vignette as:

# compute pseudobulks (sum of counts)
pb <- aggregateData(sce, 
    assay = "counts", fun = "sum",
    by = c("cluster_id", "sample_id"))
    
# run pseudobulk (aggregation-based) DS analysis
ds_pb <- pbDS(pb, method = "edgeR")

**Comment by plger** [comment]
Yes it does, but at the pseudo-bulk level. `pbDS` simply uses the normalization method of the underlying differential expression package (e.g. edgeR - this would be for instance [here](https://github.com/HelenaLC/muscat/blob/c93966305b1317b0caf5c6eb374826d6432b4a0a/R/utils-pbDS.R#L73))
Note that, because (with these parameters) the normalization happens _after_ aggregating, cells with a higher library size will have more weight in the pseudo-bulk profile. This is normally not a bad thing, since these cells also represent higher-quality information.

**Comment by pseudonym2** [comment]
Thanks, this answers my questions, and thanks for pointing me to the respective code chunks. Maybe it would be good to make it a little more clear in the vignettes though.
