### ISSUE TITLE
What is the meaning of the "scale" parameter of the "aggregateData" function?

### ISSUE THREAD

**Issue by altairwei** [HelenaLC/muscat#66]
The reference manual says:

> Should pseudo-bulks be scaled with the effective library size & multiplied by 1M?

However, the code actually does the opposite. It's divided by 1M then multiplied by ibrary size.

```R
    # compute pseudo-bulks
    pb <- .pb(x, by, assay, fun, BPPARAM)
    if (scale & length(by) == 2) {
        # compute library sizes
        cs <- if (assay == "counts" && fun == "sum")
            pb else .pb(x, by, "counts", "sum", BPPARAM)
        ls <- lapply(cs, colSums)
        # scale pseudobulks by CPM
        pb <- lapply(seq_along(pb), function(i) pb[[i]] / 1e6 * ls[[i]])
        names(pb) <- names(ls)
    }
```

If I set `scale = TRUE`, will the output of the function be CPM?

**Comment by altairwei** [comment]
@HelenaLC 
This argument is only useful when the input assay is CPM, right? Is it designed to just "scale" the CPM data?

For example:

```R
assay(sce, "cpm") <- sce %>%
  counts() %>%
  scater::calculateCPM()

pb <- muscat::aggregateData(sce, "cpm", fun = "sum", scale = TRUE)
```

**Comment by HelenaLC** [comment]
Yes, I believe so. Here a reply from my colleague (@csoneson):

*[...] The idea here is that you have CPMs as input, but you want something on the actual count scale, correct? So you divide the aggregated CPMs by 1M to get a proportion, and then you multiply with the library sizes. So what you get out is something similar to counts, but derived from the CPMs.
So yes, based on this I’d say that you don’t want to do this if the input is counts (in that case multiplying with the library size again would exacerbate the differences), and I would also prefer to use it if your aggregation is taking the mean of the CPMs rather than the sum (since with the mean the aggregated CPMs should still sum to 1M, but if you sum them they will not).*

**Comment by altairwei** [comment]
> I would also prefer to use it if your aggregation is taking the mean of the CPMs rather than the sum (since with the mean the aggregated CPMs should still sum to 1M, but if you sum them they will not).

@HelenaLC Although scaling the mean of the CPMs is preferred by @csoneson, in the actual code the `scale` parameter is disabled for the mean of the CPMs.

```
Option 'scale = TRUE' only valid for 'assay = "cpm/CPM"' and 'fun = "sum"'.
```
