### ISSUE TITLE
Error: Failed to install 'muscat' from GitHub

### ISSUE THREAD

**Issue by erikadudki** [HelenaLC/muscat#8]
Hi,
I'm trying to install muscat via: 
`install.packages("remotes")`
`remotes::install_github("HelenaLC/muscat")`

Thereby, I get the following error:
`Error: object ‘computeLibraryFactors’ is not exported by 'namespace:scater'`
`Execution halted`
`ERROR: lazy loading failed for package ‘muscat’`
`* removing ‘/home/erika/R/x86_64-pc-linux-gnu-library/3.6/muscat’`
`Error: Failed to install 'muscat' from GitHub:`
`  (converted from warning) installation of package ‘/tmp/RtmpVXQ239/file7a44305512d6``/muscat_0.99.6.tar.gz’ had non-zero exit status`

If more information is needed, just let me now.
Thanks.

**Comment by HelenaLC** [comment]
Hi Erik,
I have just answered this exact same issue, but it has been unfortunately deleted... `computeLibraryFactors` is part of `scater` 1.13+ and only available through Bioconductor version 3.10 (current development version). This is no mistake, but rather, you're likely using Bioc 3.9 at the moment.

I have recently submitted the package to Bioc & it is aimed to available for Bioc 3.10. To use this version now, 
- `BiocManager::version()` to view your current Bioc version
- `BiocManager::install(version = "devel")` to run / update to / install Bioc 3.10 (I recommend using a separate library for this rather than overwriting the stable 3.9 version of packages)

My apologies for this; I will add this as a dependancy for `muscat` ASAP to prevent further confusion.

PS: Please don't delete this issue.

**Comment by HelenaLC** [comment]
My mistake, the issue before wasn't deleted, but raised as pull request here: https://github.com/HelenaLC/muscat/pull/7

**Comment by erikadudki** [comment]
Thanks for the very fast reply! Now it works.
