### ISSUE TITLE
Setting FORCE in simData to increase the number of samples

### ISSUE THREAD

**Issue by SirKuikka** [HelenaLC/muscat#82]
Hi,

So I was just thinking what happens when I set FORCE in simData, because I want to simulate more samples (ns) than there are in the reference dataset? The package manual talks about duplicates: "number of samples to simulate; defaults to as many as available in the reference to avoid duplicated reference samples". So if I force the function to simulate more, are these extra samples going to be just duplicates of the old samples? Are they exactly the same or is there some variation in the gene expression levels? In what situation would it be beneficial to create duplicates of the same samples? Is it always better to use reference data with more samples?

**Comment by HelenaLC** [comment]
> So if I force the function to simulate more, are these extra samples going to be just duplicates of the old samples?

Well, the brief answer is yes. When you have 2 reference samples, but simulate 3, one of the simulated samples will necessarily use a reference samples that already has been used. I.e., there will be what we call *duplicates*.

> Are they exactly the same or is there some variation in the gene expression levels?
That been said, duplicates won't be *identical* as there's always some variation in sampling. 

The coefficients (betas) will be exactly the same for two simulated samples that are based on the same reference sample. The final gene means (for the NB count sampling) are computed from offsets (~ library size) and coefficients (betas).  
So there will be two sources of variability: i) offsets will vary depending on which reference cells are samples; and, ii) the NB sampling itself will introduce differences. Overall, however, both of these are solely differences in sampling, and would give near-identical samples for large N. 
 
 > In what situation would it be beneficial to create duplicates of the same samples? Is it always better to use reference data with more samples?
 
 Taken together, I think the answer to this is that i) it's probably never beneficial to introduce duplicates (because these will appear to be distinct samples when they're not really, and any model would mis-estimate the cell-cell and sample-sample variability); and, ii) it's safest to use as many reference samples as are desired for simulation.
